@startuml

class Organizacion {
    agregarDatosActividad(datosActividad)
}

Organizacion --> "1..*" DatoActividad

class DatosActividadesParser {
    separator: Character
    skipLines: Integer
    getDatosActividad()
}

DatosActividadesParser --> CSVLoader
DatosActividadesParser ..> DatoActividad : <<creates>>

class CSVLoader {
    getLineas()
}

class DatoActividad {
    valor : Double
    periodo : String
}

DatoActividad --> TipoDeConsumo
DatoActividad --> Periodicidad

enum TipoDeConsumo {
    GAS_NATURAL,
    DIESEL,
    GASOIL,
    ...
    setFactorDeEmision()
}

TipoDeConsumo --> UnidadDeConsumo

enum UnidadDeConsumo {
    M3,
    KG,
    KWH,
    ...
}

enum Periodicidad {
    MENSUAL,
    ANUAL
}

@enduml
