@startuml

class Organizacion {
    darDeAltaTrayecto(trayecto)
}

Organizacion --> "*" Trayecto

class Trayecto {
    getDistancia()
}

Trayecto --> "1..*" Tramo
Trayecto --> "1..*" Miembro

interface Tramo {
    getDistancia()
    esCompartible()
}

class TramoPrivado implements Tramo {
    inicio : Ubicacion
    fin : Ubicacion
    distancia : Distancia
}

TramoPrivado --> MedioDeTransporte

interface MedioDeTransporte {
}

MedioDeTransporte <|.. ServicioContratado
MedioDeTransporte <|.. BicicletaOPie
MedioDeTransporte <|.. VehiculoParticular

class VehiculoParticular {
    tipo : TipoDeVehiculoParticular
    combustible : TipoDeCombustible
}

ServicioContratado --> TipoDeServicioContratado

class TipoDeServicioContratado {
    nombre : String
    {static} TAXI
    {static} REMIS
}


class TramoEnTransportePublico implements Tramo {
}

TramoEnTransportePublico --> Linea
TramoEnTransportePublico --> Parada : inicio
TramoEnTransportePublico --> Parada : fin

class Linea {
    nombre : String
    tipo : TipoDeTransportePublico
    agregarParada(ubicacion)
    distanciaEntreParadas(inicio, fin)
}

Linea --> "1..*" Parada

class Parada {
    nombre : String
    distanciaAProxima : Distancia
}

@enduml
