@startuml

' ======= Organizaciones =======

class Organizacion {
    razonSocial : String
    tipo : TipoDeOrganizacion
    clasificacion : ClasificacionDeOrganizacion
    ubicacion : Ubicacion
    darDeAltaSector(sector)
}

Organizacion --> "1..*" Sector

class Sector {
    solicitarVinculacion(vinculacion)
    getVinculacionesSegunEstado(estadoVinculo)
}

Sector --> "0..*" Vinculacion : vinculaciones

class Vinculacion {
    aceptar()
    rechazar()
}

Vinculacion --> Miembro
Vinculacion -right-> EstadoVinculo

enum EstadoVinculo {
    PENDIENTE,
    ACEPTADO,
    RECHAZADO
    aceptar(vinculacion)
    rechazar(vinculacion)
}
EstadoVinculo ..> Vinculacion

class Miembro {
    nombre : String
    apellido : String
    documento : String
    tipoDeDocumento : TipoDeDocumento
}

' ======= Trayectos =======

class Organizacion {
    darDeAltaTrayecto(trayecto)
}

Organizacion --> "*" Trayecto

class Trayecto {
    getDistancia()
}

Trayecto --> "1..*" Tramo
Trayecto --> "1..*" Miembro

interface Tramo {
    getDistancia()
    esCompartible()
}

class TramoPrivado implements Tramo {
    inicio : Ubicacion
    fin : Ubicacion
    distancia : Distancia
}

TramoPrivado --> MedioDeTransporte

interface MedioDeTransporte {
}

MedioDeTransporte <|.. ServicioContratado
MedioDeTransporte <|.. BicicletaOPie
MedioDeTransporte <|.. VehiculoParticular

class VehiculoParticular {
    tipo : TipoDeVehiculoParticular
    combustible : TipoDeCombustible
}

ServicioContratado --> TipoDeServicioContratado

class TipoDeServicioContratado {
    nombre : String
    {static} TAXI
    {static} REMIS
}


class TramoEnTransportePublico implements Tramo {
}

TramoEnTransportePublico --> Linea
TramoEnTransportePublico --> Parada : inicio
TramoEnTransportePublico --> Parada : fin

class Linea {
    nombre : String
    tipo : TipoDeTransportePublico
    agregarParada(ubicacion)
    distanciaEntreParadas(inicio, fin)
}

Linea --> "1..*" Parada

class Parada {
    nombre : String
    distanciaAProxima : Distancia
}

' ======= Admins =======

class Administradores {
    agregarAdministrador(administrador)
    obtenerAdministrador(usuario, contrasena)
    existeAdministrador(usuario)
}

Administradores --> "1..*" Administrador

class Administrador {
    usuario : String
    contrasena : String
}

Administrador ..> Validador

class Validador {
    agregarValidacion()
    validar(usuario, contrasena)
}

Validador --> "0..*" Validacion

interface Validacion {
    validar(usuario, contrasena)
}

Validacion <|.. Validar8Caracteres
Validacion <|.. Validar10MilContrasenas
Validacion <|.. ValidarCaracteresConsecutivos
Validacion <|.. ValidarCaracteresRepetidos
Validacion <|.. ValidarUsuarioPorDefecto

'======= Datos de actividad =======

class Organizacion {
    agregarDatosActividad(datosActividad)
}

Organizacion --> "1..*" DatoActividad

class DatosActividadesParser {
    separator: Character
    skipLines: Integer
    getDatosActividad()
}

DatosActividadesParser --> CSVLoader
DatosActividadesParser ..> DatoActividad : <<creates>>

class CSVLoader {
    getLineas()
}

class DatoActividad {
    valor : Double
    periodo : String
}

DatoActividad --> TipoDeConsumo
DatoActividad --> Periodicidad

enum TipoDeConsumo {
    GAS_NATURAL,
    DIESEL,
    GASOIL,
    ...
    setFactorDeEmision()
}

TipoDeConsumo --> UnidadDeConsumo

enum UnidadDeConsumo {
    M3,
    KG,
    KWH,
    ...
}

enum Periodicidad {
    MENSUAL,
    ANUAL
}

@enduml
