@startuml 

    'En caso de que nos interese calcular distancias entre
    'Paradas, Direcciones, etc... Estas podrian implementar
    'Una interfaz comun.
    'La ubicacion de las paradas se podria obtener de alguna api

    interface UbicacionGeografica {
        getLatLong();
    }

    class LatLong

    class Direccion {
        Calle
        Altura
        etc...
    }

    class Parada {
        Nombre
    }

    UbicacionGeografica <|.. LatLong
    UbicacionGeografica <|.. Direccion
    UbicacionGeografica <|.. Parada

    Parada ..> LatLong
    Direccion ..> LatLong

@enduml