@startuml

node "Browser" as browser

browser -> internet

cloud "Internet" as internet {
}

internet -> sw

node "Servidor Web" as sw {
}

node CronJob as cron {
}

database "Base de datos" as db {
}

cron --> db
sw --> db

@enduml