@startuml

class Trayecto {
    fecha : LocalDate
    estaEnPeriodo(periodo) : Boolean
    getDistancia() : Double
    esCompartible() : Boolean
    carbonoEquivalente() : Double
    carbonoEquivalenteSegunConsumo(tipoDeConsumo) : Double
}


@enduml
